server:
  port: 9200
spring:
  application:
    name: user-auth
  rabbitmq:
    host: 192.168.200.128
    username: wgmao
    password: wgmao
  redis:
    host: 192.168.200.128
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.200.128:3306/wgmao_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
auth:
  ttl: 3600  #token存储到redis的过期时间
  clientId: wgmao
  clientSecret: wgmao
  cookieDomain: localhost
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/wgmao.jks
    secret: wgmaoxyz
    alias: wgmaoxyz
    password: wgmaoxyz