server:
  port: 9013
spring:
  application:
    name: comment
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 192.168.200.128
  rabbitmq:
    host: 192.168.200.128
    username: wgmao
    password: wgmao
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:3306/eureka
  instance:
    prefer-ip-address: false
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connetTimeout: 60000
        readTimeout: 20000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 20000