server:
  port: 9012
spring:
  application:
    name: article
  datasource:
    #    test1:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.200.128:3306/wgmao_article?useUnicode=true&charaterEnckding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  #    test2:
  #      driver-class-name: com.mysql.jdbc.Driver
  #      url: jdbc:mysql://192.168.200.128:3306/wgmao_user?useUnicode=true&charaterEnckding=UTF-8&serverTimezone=UTC
  #      username: root
  #      password: root
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      host: 192.168.200.128
      database: commentdb
  redis:
    host: 192.168.200.128
  rabbitmq:
    host: 192.168.200.128
    username: wgmao
    password: wgmao
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true
# Mybatis-Plus 配置
mybatis-plus:
  #  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.wgmao.article.dao
  global-config:
    id-type: 1  #0:数据库ID自增   1:用户输入id
    db-column-underline: false
    refresh-mapper: true
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true #配置的缓存的全局开关
      lazyLoadingEnabled: true #延时加载的开关
      multipleResultSetsEnabled: true #开启延时加载，否则按需加载属性
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
feign:
  hystrix:
    #    enabled: false
    enabled: true
  client:
    config:
      default:
        connetTimeout: 60000
        readTimeout: 20000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 20000